[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Raven Platform"
authors = [{name = "GTRI", email = "example@example.com"}]
dynamic = ["version", "description"]
